export type Locale = "en" | "vi";

export const DEFAULT_LOCALE: Locale = "en";

const dictionaries = {
  en: {
    navProjects: "Projects", navTeam: "Team", navOpenSource: "Open source", navSocials: "Socials", navLegits: "Legits",
    footerTitle: "Let’s build something useful.", footerDescription: "A small technology studio from Vietnam, open to thoughtful collaborations.", email: "two-tech-dev@proton.me",
    localeEnglish: "EN", localeVietnamese: "VI", localeLabel: "Language", skipContent: "Skip to content", contributor: "Contributor", viewOrganization: "View organization ↗",
    legitsEyebrow: "Trust / Transaction history", legitsSource: "Transaction records", legitsScroll: "Scroll transaction history", legitsLive: "Recorded on Discord", legitsMore: "Load older transactions", legitsTitle: "Legits", legitsDescription: "Public receipts and completed transactions for checking 2Tech’s trading reputation.", legitsLoading: "Loading transactions…", legitsLoadMore: "Loading older transactions…", legitsEmpty: "No transactions recorded yet.", legitsRetry: "Try again", legitsUnavailable: "Transaction history is temporarily unavailable.", legitsEnd: "You’ve reached the earliest transaction.", legitsReply: "Related transaction", legitsAttachment: "Receipt", legitsEmbed: "Transaction link",
    contributionsUnavailable: "Contribution data is temporarily unavailable.", contributionsLoading: "Loading contribution data…", contributionsRank: "Rank", contributionsEngineer: "Engineer", contributionsCommits: "Commits", contributionsRole: "Role", contributionsTitle: "Built in the open.", contributionsDescription: "A live view of contribution activity across the 2Tech Studio GitHub organization.",
    homeEyebrow: "Vietnam-based product studio", homeTitle: "We make digital things feel simple.", homeDescription: "From game servers to payment systems, we build software that works well, looks good, and helps people get things done.", homeWork: "See our work", homeTeam: "Meet the team", homeStudioView: "2Tech / Studio view", homeCaption: "People first. Systems second. Good work, together.", homeProjects: "projects in the studio", homePeople: "people making things", homeRefresh: "GitHub refresh window", selectedWork: "Selected work", builtCare: "Built with care.", allProjects: "View all projects", howWork: "How we work", clearSteps: "Clear steps. No mystery.", frame: "Frame", frameDescription: "Understand the problem and make the next step clear.", build: "Build", buildDescription: "Shape the right product with the right level of detail.", ship: "Ship", shipDescription: "Put useful software in people’s hands and keep improving it.", contactEyebrow: "Have something in mind?", contactTitle: "Let’s make it feel right.", contactDescription: "Tell us what you’re working on. We’ll reply with a thoughtful next step.", startProject: "Start a project", footerRights: "All rights reserved.", activity: "Activity",
    projectsEyebrow: "Projects / Our work", projectsTitle: "Things we’re proud to put our name on.", projectsDescription: "A selection of products, platforms, and tools built by the 2Tech Studio team.", featuredWork: "More from the studio", readCase: "Read case study", more: "more", backProjects: "Back to projects", viewLive: "View live", sourceCode: "Source code", overview: "Overview", problem: "The problem", approach: "Our approach", highlights: "Highlights", techStack: "Tech stack", nextProject: "Next project",
    teamEyebrow: "People / The team", teamTitle: "Good work starts with good people.", teamDescription: "A small group that moves fast, communicates clearly, and ships things people actually use.",
    socialEyebrow: "Socials / Stay connected", socialTitle: "Come say hi.", socialDescription: "Follow the studio, join the conversation, and see what we’re learning along the way.",
    socialDiscord: "Join our community server", socialFacebook: "Follow our fanpage", socialX: "Follow us on X", socialYouTube: "Watch our content",
    contribBoard: "Contribution board", contribPeople: "People making progress", contribGithub: "View on GitHub ↗", rank: "Rank", engineer: "Engineer", commits: "Commits", role: "Role",
  },
  vi: {
    navProjects: "Dự án", navTeam: "Đội ngũ", navOpenSource: "Mã nguồn mở", navSocials: "Kết nối", navLegits: "Uy tín",
    footerTitle: "Cùng xây điều hữu ích.", footerDescription: "Một studio công nghệ nhỏ từ Việt Nam, luôn sẵn sàng cho những hợp tác tử tế.", email: "two-tech-dev@proton.me",
    localeEnglish: "EN", localeVietnamese: "VI", localeLabel: "Ngôn ngữ", skipContent: "Đến nội dung chính", contributor: "Người đóng góp", viewOrganization: "Xem tổ chức trên GitHub ↗",
    legitsEyebrow: "Uy tín / Lịch sử giao dịch", legitsSource: "Giao dịch đã ghi nhận", legitsScroll: "Cuộn lịch sử giao dịch", legitsLive: "Đối soát từ Discord", legitsMore: "Xem giao dịch cũ hơn", legitsTitle: "Legits", legitsDescription: "Hóa đơn và giao dịch đã hoàn tất, được lưu công khai để kiểm tra uy tín của 2Tech.", legitsLoading: "Đang tải giao dịch…", legitsLoadMore: "Đang tải giao dịch cũ hơn…", legitsEmpty: "Chưa có giao dịch nào được ghi nhận.", legitsRetry: "Thử lại", legitsUnavailable: "Lịch sử giao dịch hiện chưa khả dụng.", legitsEnd: "Bạn đã xem đến giao dịch đầu tiên.", legitsReply: "Giao dịch liên quan", legitsAttachment: "Hóa đơn", legitsEmbed: "Liên kết giao dịch",
    contributionsUnavailable: "Chưa thể tải dữ liệu đóng góp.", contributionsLoading: "Đang tải dữ liệu đóng góp…", contributionsRank: "Hạng", contributionsEngineer: "Người đóng góp", contributionsCommits: "Đóng góp", contributionsRole: "Vai trò", contributionsTitle: "Cùng nhau xây dựng công khai.", contributionsDescription: "Theo dõi hoạt động đóng góp của đội ngũ 2Tech Studio trên GitHub.",
    homeEyebrow: "Studio sản phẩm công nghệ từ Việt Nam", homeTitle: "Làm sản phẩm số dễ dùng hơn.", homeDescription: "Từ server game đến hệ thống thanh toán, chúng tôi xây phần mềm tốt, đẹp và giúp mọi người hoàn thành việc của mình.", homeWork: "Xem dự án", homeTeam: "Gặp đội ngũ", homeStudioView: "2Tech / Góc studio", homeCaption: "Con người trước. Hệ thống sau. Cùng nhau làm tốt.", homeProjects: "dự án trong studio", homePeople: "người đang xây dựng", homeRefresh: "Chu kỳ cập nhật GitHub", selectedWork: "Dự án tiêu biểu", builtCare: "Làm bằng sự tử tế.", allProjects: "Xem tất cả dự án", howWork: "Cách chúng tôi làm việc", clearSteps: "Rõ ràng từng bước.", frame: "Định hình", frameDescription: "Hiểu đúng bài toán và làm rõ bước tiếp theo.", build: "Xây dựng", buildDescription: "Tạo sản phẩm vừa đủ, đúng nhu cầu và chi tiết cần thiết.", ship: "Ra mắt", shipDescription: "Đưa phần mềm hữu ích đến tay mọi người rồi tiếp tục hoàn thiện.", contactEyebrow: "Bạn đang có một ý tưởng?", contactTitle: "Cùng làm cho nó thật đúng.", contactDescription: "Kể chúng tôi nghe bạn đang làm gì. Chúng tôi sẽ trả lời bằng một bước tiếp theo rõ ràng.", startProject: "Bắt đầu dự án", footerRights: "Đã đăng ký bản quyền.", activity: "Hoạt động",
    projectsEyebrow: "Dự án / Sản phẩm", projectsTitle: "Những thứ chúng tôi tự hào làm ra.", projectsDescription: "Một số sản phẩm, nền tảng và công cụ do đội ngũ 2Tech Studio xây dựng.", featuredWork: "Các dự án khác", readCase: "Xem chi tiết dự án", more: "dự án khác", backProjects: "Về danh sách dự án", viewLive: "Xem sản phẩm", sourceCode: "Mã nguồn", overview: "Tổng quan", problem: "Bài toán", approach: "Cách làm", highlights: "Điểm nổi bật", techStack: "Công nghệ sử dụng", nextProject: "Dự án tiếp theo",
    teamEyebrow: "Con người / Đội ngũ", teamTitle: "Việc tốt bắt đầu từ người phù hợp.", teamDescription: "Một nhóm nhỏ làm việc nhanh, nói chuyện rõ ràng và tạo ra những thứ mọi người thật sự dùng.",
    socialEyebrow: "Kết nối / Cộng đồng", socialTitle: "Ghé qua trò chuyện.", socialDescription: "Theo dõi studio, tham gia cộng đồng và xem chúng tôi đang làm gì.",
    socialDiscord: "Tham gia cộng đồng Discord", socialFacebook: "Theo dõi trang Facebook", socialX: "Theo dõi trên X", socialYouTube: "Xem video mới nhất",
    contribBoard: "Bảng đóng góp", contribPeople: "Những người đang tiến bước", contribGithub: "Xem trên GitHub ↗", rank: "Hạng", engineer: "Người đóng góp", commits: "Đóng góp", role: "Vai trò",
  },
} as const;

export type TranslationKey = keyof typeof dictionaries.en;
export function translate(locale: Locale, key: TranslationKey): string { return dictionaries[locale][key] ?? dictionaries.en[key]; }
export function isLocale(value: string | null): value is Locale { return value === "en" || value === "vi"; }
