"use client";

import Image from "next/image";
import Link from "next/link";
import { useLocale } from "@/components/i18n/LocaleProvider";
import type { Project } from "@/data/projects";
import type { TranslationKey } from "@/lib/i18n";

export function ProjectDetailContent({ project, next }: { project: Project; next: Project }) {
  const { t } = useLocale();
  const sections: [TranslationKey, string | undefined][] = [["overview", project.overview], ["problem", project.problem], ["approach", project.solution]];
  return <><header className="site-wrap pb-10 pt-12 sm:pb-16 sm:pt-20"><Link href="/projects" className="text-link text-sm">← {t("backProjects")}</Link><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_18rem] lg:items-end"><div><div className="flex flex-wrap items-center gap-3"><span className="status">{project.status}</span><span className="text-sm text-[var(--color-ink-muted)]">{project.date}</span></div><h1 className="display mt-5 text-[clamp(3.4rem,9vw,7rem)]">{project.title}</h1><p className="lead mt-6 max-w-2xl text-lg">{project.tagline}</p></div><div className="flex flex-wrap gap-2 lg:justify-end">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></header><section className="site-wrap"><div className="soft-surface flex min-h-80 items-center justify-center overflow-hidden p-10 sm:min-h-[34rem]"><Image src={project.icon || "/logo-2tech.png"} alt={`${project.title} logo`} width={440} height={440} className="size-64 object-contain sm:size-96" /></div><div className="mt-5 flex flex-wrap gap-3">{project.links.live && <a href={project.links.live} target="_blank" rel="noopener noreferrer" className="primary-button">{t("viewLive")} ↗</a>}{project.links.github && <a href={project.links.github} target="_blank" rel="noopener noreferrer" className="secondary-button">{t("sourceCode")} ↗</a>}</div></section><section className="site-wrap site-section grid gap-12 lg:grid-cols-[minmax(0,1fr)_19rem]"><article className="max-w-3xl space-y-14">{sections.map(([key, body]) => <section key={key}><p className="eyebrow">{t(key)}</p><h2 className="display mt-4 text-4xl sm:text-5xl">{t(key)}</h2><p className="mt-5 text-base leading-8 text-[var(--color-ink-muted)] sm:text-lg">{body}</p></section>)}<section><p className="eyebrow">{t("highlights")}</p><div className="mt-5 space-y-3">{project.highlights.map((item, index) => <div key={item} className="surface flex gap-4 p-4"><span className="font-mono text-sm text-[var(--color-accent)]">0{index + 1}</span><span className="text-sm leading-6">{item}</span></div>)}</div></section></article><aside className="soft-surface h-fit p-5 lg:sticky lg:top-24"><p className="eyebrow">{t("techStack")}</p><div className="mt-5 space-y-3">{project.techStack.map((tech) => <div key={tech.name} className="flex items-center justify-between gap-3 border-b border-[var(--color-border)] pb-3"><span className="text-sm font-semibold">{tech.name}</span><span className="text-right text-xs text-[var(--color-ink-muted)]">{tech.category}</span></div>)}</div></aside></section><Link href={`/projects/${next.slug}`} className="block border-y border-[var(--color-border)] bg-[var(--color-surface)]"><div className="site-wrap flex items-center justify-between gap-4 py-8"><span className="text-sm text-[var(--color-ink-muted)]">{t("nextProject")}</span><strong className="text-xl font-bold tracking-[-0.04em] sm:text-2xl">{next.title} →</strong></div></Link></>;
}
