"use client";

import Image from "next/image";
import Link from "next/link";
import { useLocale } from "@/components/i18n/LocaleProvider";
import { projects } from "@/data/projects";

export function ProjectsContent() {
  const { t } = useLocale();
  const [featured, ...rest] = projects;
  return <><header className="site-wrap pb-12 pt-12 sm:pb-16 sm:pt-20"><p className="eyebrow">{t("projectsEyebrow")}</p><h1 className="display mt-5 max-w-4xl text-[clamp(3rem,8vw,6rem)]">{t("projectsTitle")}</h1><p className="lead mt-6 max-w-xl">{t("projectsDescription")}</p></header>{featured && <section className="site-wrap pb-12"><Link href={`/projects/${featured.slug}`} className="surface card-lift grid overflow-hidden lg:grid-cols-[1.1fr_0.9fr]"><div className="flex min-h-80 items-center justify-center bg-[var(--color-surface-soft)] p-10 sm:min-h-[28rem]"><Image src={featured.icon || "/logo-2tech.png"} alt={`${featured.title} logo`} width={360} height={360} className="size-64 object-contain transition-transform duration-500 hover:scale-105 sm:size-80" /></div><div className="flex flex-col justify-center p-7 sm:p-10"><div className="flex items-center justify-between"><span className="status">{featured.status}</span><span className="text-sm text-[var(--color-ink-muted)]">{featured.date}</span></div><h2 className="display mt-6 text-5xl sm:text-7xl">{featured.title}</h2><p className="lead mt-5 text-base">{featured.tagline}</p><span className="text-link mt-8">{t("readCase")} →</span></div></Link></section>}<section className="site-wrap site-section pt-8"><div className="mb-6 flex items-center justify-between"><p className="eyebrow">{t("featuredWork")}</p><span className="text-sm text-[var(--color-ink-muted)]">{rest.length} {t("more")}</span></div><div className="divide-y divide-[var(--color-border)] border-y border-[var(--color-border)]">{rest.map((project, index) => <Link href={`/projects/${project.slug}`} key={project.slug} className="group grid min-w-0 gap-4 py-6 sm:grid-cols-[3rem_5rem_minmax(0,1fr)_auto] sm:items-center"><span className="font-mono text-sm text-[var(--color-accent)]">0{index + 2}</span><div className="flex size-16 items-center justify-center rounded-[var(--radius-sm)] bg-[var(--color-surface-soft)] p-2"><Image src={project.icon || "/logo-2tech.png"} alt="" width={56} height={56} className="size-full object-contain" /></div><div className="min-w-0"><h2 className="text-xl font-bold tracking-[-0.04em] group-hover:text-[var(--color-accent-hover)]">{project.title}</h2><p className="mt-1 truncate text-sm text-[var(--color-ink-muted)]">{project.tagline}</p></div><span className="status justify-self-start sm:justify-self-end">{project.status}</span></Link>)}</div></section></>;
}
